language: python

python:
  - 3.6

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE orders;" -U postgres
  - python manage.py migrate --noinput
  

script:
  - pytest
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: "22574351-c089-41ba-a781-63af7977c453"
  app: backend-challenge5
  on: main
  strategy: git