dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:

    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        - docker-compose -f docker-compose.yml build
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose exec web python -m manage migrate

        - docker-compose -f docker-compose.yml up -d
      script:
        - docker-compose  exec web pytest
      after_failure:
        - docker-compose -f docker-compose.yml logs