language: python

python:
  - 3.6

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE orders;" -U postgres
  - python manage.py migrate --noinput
  

script:
  - pytest
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
      secure: "na9PX5GEP7ytmjxb5GYRVVqJEvIQcwzRRuPouDiTmGumE0SjNegwClVK3iDvvFbUr3we8Tyb6KAq6QDgWOZydwnsRdayab94d+KN7jbFdLYogb5zO0cptrRuLEF5W9kQ7VxE3sIoPBKksl/1etz8IvH5RnIjbQP4crm5E3hScw/+imk92D58NrOS5FU0HrK/HtiWM4NyEG8JbCF9p38OLVp3QgABpKQ3NPuAqO7ezzgXewTvWpIkUoognKU3KP9MvwCCfHde7w2aNO0bzl3m2ctj/4pFj8aGi6hUDtX6we7d9+l4Jzu5cZwCGsA/JCoYf4JriLVPKzkdDRuyiOaVM+Ik92TpVUhViyqvL6E+gTuHP9CVBnpHkFnEYFZHgE4lcHeoDVFqAx0Vny1iDTs5+R18xBTmOrBCNNM2JHpxNqirdv3BFsSA700WEANveYQ+eHJ4DgOIGTgpJyNXop9k+9pYQ7zmpTwPySshUs2j2PJcw+TEEc1yK5ImKnx/zU3FjJxNJwWh8pmPeHcaXK837+qANQkEDJKzWNQzk9BTGDsLhOJdueJJGEWg/e5enOwUKGlOgKCZfCmU5YjiYjt2bzwXdyd/lxJpLoJJ0cw01Bx9Vvr/KKKkzncOxoplXioFLH7bqSrYGYm0/7wT8rFbs60vOv8ynBgYSIEmzD0NFoA="
  app: backend-challenge5
  on: main
  strategy: git