dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:

    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        - docker-compose -f docker-compose.yml build
        # Ensure celerybeat does not crash due to non-existent tables
       

        - docker-compose -f docker-compose.yml up -d
        - docker-compose -f docker-compose.yml run web python manage.py migrate
      script:
        -docker-compose run web pytest
    
      after_failure:
        - docker-compose -f docker-compose.yml logs