version: "2.5"
   
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - SECRET_KEY=+63moyr!(3^666l62(@^u$zt!s1)ofxg^
      - DEBUG=True
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lucy
    expose:
      - 5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=+63moyr!(3^666l62(@^u$zt!s1)ofxg^
      - DEBUG=True
      - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - OIDC_RP_CLIENT_ID=1084835314828-s8npea9jce01udttaf8td5627p9k06fg.apps.googleusercontent.com
      - OIDC_RP_CLIENT_SECRET=4ZbM0GBZVisPA9YrBP3lFcr5   
      - AFRICASTALKING_API_KEY=4b687203c43211be0e43105531bf92d7d8ad44d778bdfcf869988c465049291e
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lucy 
    depends_on:
      - db
  celery:
    build: .
    command: celery -A backend_challenge worker -l INFO
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=+63moyr!(3^666l62(@^u$zt!s1)ofxg^
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine
volumes:
  postgres_data:  
  

