# Generated by Django 4.1.8 on 2023-06-18 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0006_alter_location_cords"),
        ("trips", "0012_rename_driver_displayname_trip_driver"),
        ("organization", "0009_alter_organization_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "stop_status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("IP", "In Progress"),
                            ("EN", "In Progress"),
                            ("CL", "Cancel"),
                            ("C", "Completed"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The sequence of the stop in the trip.",
                        verbose_name="Sequence",
                    ),
                ),
                (
                    "eta",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time the vehicle is expected to arrive at the stop.",
                        null=True,
                        verbose_name="Stop ETA ",
                    ),
                ),
                (
                    "arrival_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time the vehicle actually arrived at the stop.",
                        null=True,
                        verbose_name="Stop Arrival Time",
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time the vehicle actually departed from the stop.",
                        null=True,
                        verbose_name="Stop Departure Time",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="The location of the stop.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stops",
                        related_query_name="stop",
                        to="locations.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        help_text="The trip that the stop belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stop",
                "verbose_name_plural": "Stops",
            },
        ),
    ]
