# Generated by Django 3.1 on 2023-02-16 16:58

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+254234567892'. Up to 12 digits allowed with no", regex='^\\+254\\d{9}$')])),
                ('national_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('capacity', models.PositiveIntegerField(null=True)),
                ('availability_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('scac_code', models.CharField(help_text='The SCAC code for the organization.', max_length=4, verbose_name='SCAC Code')),
                ('org_type', models.CharField(choices=[('Asset', 'Asset'), ('Brokerage', 'Brokerage'), ('Both', 'Both')], default='Asset', help_text='The type of organization.', max_length=10, verbose_name='Organization Type')),
                ('currency', models.CharField(default='USD', help_text='The currency that the organization uses', max_length=255, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('no_plate', models.CharField(max_length=15, unique=True, verbose_name='No Plate')),
                ('capacity', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, editable=False, max_length=100)),
                ('distance', models.CharField(blank=True, max_length=100, null=True)),
                ('load', models.CharField(blank=True, max_length=100)),
                ('utilization', models.CharField(blank=True, editable=False, max_length=100)),
                ('num_deliveries', models.CharField(blank=True, default=1, editable=False, max_length=100)),
                ('depature_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('fuel_consumption', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_completion_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('dispatched', 'dispatched'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='pending', max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_trips', to='core.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('selection', models.CharField(choices=[('Min_Distance', 'Balance Vehicle Utilization and Driving Time'), ('Min_Veh', 'Minimum Vehicle(Maximize Vehicle  Capacity )'), ('MU', 'Manual')], default='Min_Distance', max_length=255, verbose_name='Vehicle Selection')),
                ('start_address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'verbose_name': 'RouteSettings',
                'verbose_name_plural': 'RouteSettings',
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='The name of the depot.', max_length=255, unique=True, verbose_name='Depot Name')),
                ('description', models.TextField(blank=True, help_text='The description of the depot.', max_length=255, verbose_name='Depot Description')),
                ('address_line_1', models.CharField(help_text='The address line 1 of the depot.', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='The address line 2 of the depot.', max_length=255, verbose_name='Address Line 2')),
                ('cordinates', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.798107, -1.283922), srid=4326)),
                ('city', models.CharField(help_text='The city of the depot.', max_length=255, verbose_name='City')),
                ('organization', models.ForeignKey(help_text='The organization that the depot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='depots', related_query_name='depot', to='core.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Hub',
                'verbose_name_plural': 'Hubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('delivery_adress', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+254234567892'. Up to 12 digits allowed with no", regex='^\\+254\\d{9}$')])),
                ('weight', models.PositiveIntegerField(default=1, help_text='For Route Optimization purposes', verbose_name='Quantity/Weight')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('delivered', 'delivered'), ('assigned', 'assigned')], default='pending', max_length=20)),
                ('earliest', models.DateTimeField(blank=True, null=True)),
                ('latest', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_in_trip', to='core.trip')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
