# Generated by Django 3.1.1 on 2023-01-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='location',
            new_name='point',
        ),
    ]
