# Generated by Django 3.1 on 2023-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesettings',
            name='end_location',
            field=models.CharField(choices=[('Min_Distance', 'Balance Vehicle Utilization and Driving Time'), ('Min_Veh', 'Minimum Vehicle(Maximize Vehicle  Capacity )'), ('MU', 'Manual')], default='Kilimani', max_length=255, verbose_name='End Location'),
        ),
        migrations.AddField(
            model_name='routesettings',
            name='start_location',
            field=models.CharField(choices=[('Min_Distance', 'Balance Vehicle Utilization and Driving Time'), ('Min_Veh', 'Minimum Vehicle(Maximize Vehicle  Capacity )'), ('MU', 'Manual')], default='Kilimani', max_length=255, verbose_name='Start Location'),
        ),
    ]
