# Generated by Django 3.1 on 2023-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_url',
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
