# Generated by Django 3.1 on 2023-02-24 01:58

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesettings',
            name='end_address',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.7866471, -1.2981014), srid=4326),
        ),
        migrations.AlterField(
            model_name='routesettings',
            name='start_address',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.7866471, -1.2981014), srid=4326),
        ),
    ]
