# Generated by Django 3.1 on 2023-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230216_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesettings',
            name='end_location',
            field=models.CharField(choices=[('Kilimani', 'Kilimani Hub'), ('Rongai  ', 'Rongai hub )')], default='Kilimani', max_length=255, verbose_name='End Location'),
        ),
        migrations.AlterField(
            model_name='routesettings',
            name='selection',
            field=models.CharField(choices=[('Min_Distance', 'Balance Vehicle Utilization and Driving Time'), ('Min_Veh', 'Minimum Vehicle(Maximize Vehicle  Capacity )'), ('MU', 'Manual')], default='Min_Veh', max_length=255, verbose_name='Vehicle Selection'),
        ),
        migrations.AlterField(
            model_name='routesettings',
            name='start_location',
            field=models.CharField(choices=[('Kilimani', 'Kilimani Hub'), ('Rongai  ', 'Rongai hub )')], default='Kilimani', max_length=255, verbose_name='Start Location'),
        ),
    ]
