# Generated by Django 3.1 on 2023-02-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230219_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='depature_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('dispatched', 'dispatched'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
