# Generated by Django 3.1.1 on 2022-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221226_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'electronics'), ('fashion', 'fashion')], default='fashion', max_length=16, verbose_name='Category'),
        ),
    ]
