# Generated by Django 3.1 on 2023-02-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230219_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
    ]
