# Generated by Django 3.1.1 on 2022-12-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
