# Generated by Django 3.1 on 2023-01-06 01:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230104_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('vehicle_utilization', models.CharField(choices=[('AU', 'Automatic'), ('MU', 'Manual')], default='AU', max_length=2)),
                ('mode', models.CharField(choices=[('D', 'Min Distance'), ('A', 'Arrival Time'), ('B', 'Balance Distance and Arrival Time')], default='D', max_length=2)),
                ('start_address', django.contrib.gis.db.models.fields.PointField(default=(-1.283922, 36.798107), srid=4326)),
                ('end_address', django.contrib.gis.db.models.fields.PointField(default=(-1.283922, 36.798107), srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='point',
            new_name='delivery_adress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='delivery_point',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
