# Generated by Django 3.1 on 2023-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230216_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesettings',
            name='selection',
            field=models.CharField(choices=[('Min_Veh', 'Maximize Available Fleet   Capacity(Minimum Vehicle)'), ('Min_Distance', 'Balance Fleet Capacity  and Driving Time'), ('MU', 'Manual Vehicle Selection')], default='Min_Veh', max_length=255, verbose_name='Vehicle Selection'),
        ),
    ]
