# Generated by Django 3.1 on 2023-02-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_auto_20230220_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='location_cordinates',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_title', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
