# Generated by Django 3.1 on 2023-01-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230106_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('paid', 'paid'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='draft', max_length=20),
        ),
    ]
