# Generated by Django 3.1 on 2023-02-21 19:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230221_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='location_cordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
