# Generated by Django 3.1 on 2023-02-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hub_location_cordinates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hub',
        ),
    ]
