# Generated by Django 3.1 on 2023-01-06 02:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesettings',
            name='end_address',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.798107, -1.283922), srid=4326),
        ),
        migrations.AlterField(
            model_name='routesettings',
            name='start_address',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.798107, -1.283922), srid=4326),
        ),
    ]
