# Generated by Django 3.1 on 2023-01-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230106_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
