# Generated by Django 3.1 on 2023-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230224_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesettings',
            name='avoid_highways',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routesettings',
            name='avoid_tolls',
            field=models.BooleanField(default=True),
        ),
    ]
