# Generated by Django 3.1 on 2023-01-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesettings',
            name='vehicle_capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='OrderShipment',
        ),
    ]
