# Generated by Django 3.1 on 2023-03-02 23:19

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shippingcontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('delivery_adress', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.7866471, -1.2981014), srid=4326)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+254234567892'. Up to 12 digits allowed with no", regex='^\\+254\\d{9}$')])),
                ('plannedLocation', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.7866471, -1.2981014), srid=4326)),
                ('weight', models.PositiveIntegerField(default=1, help_text='For Route Optimization purposes', verbose_name='Quantity/Weight')),
                ('earliest', models.DateTimeField(blank=True, null=True)),
                ('latest', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
