# Generated by Django 3.1 on 2023-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230109_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesettings',
            name='mode',
            field=models.CharField(choices=[('Minimum Distance', 'Min Distance'), ('Ensure Arrival Time', 'Arrival Time'), ('Balance Distance and Arrival Times ', 'Balance Distance and Arrival Time')], default='Minimum Distance', max_length=255),
        ),
    ]
