# Generated by Django 3.1 on 2023-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_code',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
