# Generated by Django 3.1 on 2023-03-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_trip_trip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesettings',
            name='org',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_code',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
