# Generated by Django 3.1 on 2023-03-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('core', '0012_auto_20230313_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesettings',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.organization'),
        ),
    ]
