# Generated by Django 3.1 on 2023-01-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='code',
        ),
    ]
