# Generated by Django 3.1 on 2023-01-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_driver_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('no_plate', models.CharField(max_length=15, unique=True, verbose_name='No Plate')),
                ('capacity', models.PositiveIntegerField()),
                ('allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
