# Generated by Django 3.1 on 2023-01-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesettings',
            name='vehicle_capacity',
        ),
    ]
