# Generated by Django 3.1 on 2023-01-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230116_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('driver', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='routesettings',
            name='mode',
            field=models.CharField(choices=[('Minimize Distance', 'Minimize Distance'), ('Ensure Arrival Time', 'Arrival Time'), ('Balance Distance and Arrival Times ', 'Balance Distance and Arrival Time')], default='Minimize Distance', max_length=255),
        ),
    ]
