# Generated by Django 3.1 on 2023-01-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230116_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='routesettings',
            options={'verbose_name': 'RouteSettings', 'verbose_name_plural': 'RouteSettings'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='For Route Optimization purposes', verbose_name='Quantity/Weight'),
        ),
    ]
