# Generated by Django 3.1 on 2023-01-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230117_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesettings',
            name='mode',
            field=models.CharField(choices=[('Min_Distance', 'Minimize Distance'), ('Ensure Arrival Time', 'Arrival Time'), ('Min_Vehicles', 'Minimum Vehicle')], default='Min_Distance', max_length=255),
        ),
    ]
