# Generated by Django 3.1 on 2023-01-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230117_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesettings',
            name='vehicle_selection',
        ),
        migrations.AddField(
            model_name='routesettings',
            name='selection',
            field=models.CharField(choices=[('Min_Veh', 'Minimum Vehicle'), ('Min_Distance', 'Balance Distance and Vehicle Utilization'), ('MU', 'Manual')], default='Min_Distance', max_length=255, verbose_name='Vehicle Selection'),
        ),
    ]
