# Generated by Django 3.1 on 2023-01-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230117_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesettings',
            name='mode',
        ),
    ]
