# Generated by Django 3.1 on 2023-01-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_routesettings_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesettings',
            name='avoid_highways',
            field=models.BooleanField(null=True),
        ),
    ]
