# Generated by Django 3.1 on 2023-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_routesettings_avoid_highways'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='earliest',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='latest',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routesettings',
            name='depature_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='routesettings',
            name='selection',
            field=models.CharField(choices=[('Min_Distance', 'Balance Distance and Vehicle Utilization'), ('Min_Veh', 'Minimum Vehicle'), ('MU', 'Manual')], default='Min_Distance', max_length=255, verbose_name='Vehicle Selection'),
        ),
    ]
