# Generated by Django 3.1 on 2023-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20230127_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesettings',
            name='end_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
