# Generated by Django 3.1 on 2023-01-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_routesettings_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
