# Generated by Django 3.1 on 2023-01-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230131_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='load',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
