# Generated by Django 3.1 on 2023-01-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_trip_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
    ]
