# Generated by Django 3.1 on 2023-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230131_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='utilization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
