# Generated by Django 3.1 on 2023-01-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230131_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_deliveries', to='core.trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='depature_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
