# Generated by Django 3.1 on 2023-01-31 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20230201_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_trips', to='core.driver'),
        ),
    ]
