# Generated by Django 3.1 on 2023-01-31 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_trip_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
    ]
