# Generated by Django 3.1 on 2023-01-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_trip_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='num_deliveries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
