# Generated by Django 3.1 on 2023-01-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_trip_num_deliveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='num_deliveries',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
    ]
