# Generated by Django 3.1 on 2023-02-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20230201_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesettings',
            name='end_time',
        ),
        migrations.AddField(
            model_name='routesettings',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
