# Generated by Django 3.1 on 2023-02-01 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20230201_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesettings',
            name='depature_time',
            field=models.TimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='num_deliveries',
            field=models.CharField(blank=True, default=1, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='utilization',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
