# Generated by Django 3.1 on 2023-02-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20230201_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
