# Generated by Django 3.1 on 2023-02-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230201_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesettings',
            name='service_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
