# Generated by Django 3.1 on 2023-02-09 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_routesettings_service_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='address',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone',
            field=models.CharField(default=254728826517, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+254234567892'. Up to 12 digits allowed with no", regex='^\\+254\\d{9}$')]),
            preserve_default=False,
        ),
    ]
