# Generated by Django 3.1 on 2023-02-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20230209_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='destination',
            new_name='address',
        ),
    ]
