# Generated by Django 3.1 on 2023-02-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20230209_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='rider',
            new_name='driver',
        ),
        migrations.AddField(
            model_name='trip',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
