# Generated by Django 3.1 on 2023-02-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20230212_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumption',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
