# Generated by Django 3.1 on 2023-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20230212_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
