# Generated by Django 4.1.8 on 2023-06-05 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0002_remove_routesettings_end_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routesettings",
            name="selection",
        ),
    ]
