# Generated by Django 4.1.8 on 2023-06-07 00:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_alter_location_cords"),
        ("routeplanning", "0004_alter_routesettings_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routesettings",
            name="departure_time",
            field=models.TimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
        ),
        migrations.AlterField(
            model_name="routesettings",
            name="end_point",
            field=models.ForeignKey(
                blank=True,
                help_text="optional,Select the endpoint of your route",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="route_end",
                to="locations.location",
                verbose_name="end point",
            ),
        ),
    ]
