# Generated by Django 4.1.8 on 2023-06-07 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0006_alter_routesettings_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routesettings",
            name="departure_time",
            field=models.TimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 7, 0, 25, 39, 261241, tzinfo=datetime.timezone.utc
                ),
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
        ),
    ]
