# Generated by Django 4.1.8 on 2023-06-07 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0007_alter_routesettings_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routesettings",
            name="departure_time",
            field=models.TimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 7, 0, 47, 34, 659857, tzinfo=datetime.timezone.utc
                ),
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
        ),
        migrations.AlterField(
            model_name="routesettings",
            name="service_time",
            field=models.PositiveIntegerField(
                help_text="average time taken to complete a task",
                verbose_name="Service time(mins)",
            ),
        ),
    ]
