# Generated by Django 4.1.8 on 2023-06-07 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0008_alter_routesettings_departure_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routesettings",
            name="start_options",
            field=models.CharField(
                choices=[
                    ("F", "Select from Locations/Branches"),
                    ("DA", "Driver Current Address"),
                ],
                default="F",
                max_length=255,
                verbose_name="Start Options",
            ),
        ),
        migrations.AlterField(
            model_name="routesettings",
            name="departure_time",
            field=models.TimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 7, 1, 52, 15, 187862, tzinfo=datetime.timezone.utc
                ),
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
        ),
        migrations.AlterField(
            model_name="routesettings",
            name="finish_time",
            field=models.TimeField(blank=True, help_text="optional,", null=True),
        ),
    ]
