# Generated by Django 4.1.8 on 2023-06-09 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_alter_location_cords"),
        ("routeplanning", "0009_routesettings_start_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routesettings",
            name="departure_time",
            field=models.TimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 9, 21, 5, 21, 515350, tzinfo=datetime.timezone.utc
                ),
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
        ),
        migrations.AlterField(
            model_name="routesettings",
            name="end_point",
            field=models.ForeignKey(
                blank=True,
                help_text="optional,Select the endpoint of your route",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_end",
                to="locations.location",
                verbose_name="end point",
            ),
        ),
        migrations.AlterField(
            model_name="routesettings",
            name="start_point",
            field=models.ForeignKey(
                help_text="Route Origin",
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.location",
                verbose_name="start point",
            ),
        ),
    ]
