# Generated by Django 4.1.8 on 2023-06-09 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0011_alter_routesettings_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routesettings",
            name="departure_time",
            field=models.TimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 9, 23, 50, 22, 209798, tzinfo=datetime.timezone.utc
                ),
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
        ),
    ]
