# Generated by Django 4.1.8 on 2023-06-11 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0015_alter_routesettings_departure_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routesettings",
            name="departure_time",
        ),
    ]
