# Generated by Django 4.1.8 on 2023-06-12 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0016_remove_routesettings_departure_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="routesettings",
            name="departure_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
            preserve_default=False,
        ),
    ]
