# Generated by Django 4.1.8 on 2023-06-15 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0018_routesettings_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routesettings",
            old_name="user",
            new_name="org_user",
        ),
    ]
