# Generated by Django 4.1.8 on 2023-06-15 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0022_alter_routesettings_org_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routesettings",
            name="departure_time",
        ),
        migrations.RemoveField(
            model_name="routesettings",
            name="finish_time",
        ),
    ]
