# Generated by Django 4.1.8 on 2023-06-15 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0023_remove_routesettings_departure_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routesettings",
            name="end_time",
            field=models.DateTimeField(blank=True, help_text="optional,", null=True),
        ),
        migrations.AddField(
            model_name="routesettings",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="set future time, defaults to now, for eta  calculation and route optimization purposes",
            ),
            preserve_default=False,
        ),
    ]
