# Generated by Django 4.1.8 on 2023-06-15 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0024_routesettings_end_time_routesettings_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routesettings",
            old_name="start_time",
            new_name="departure_time",
        ),
    ]
