# Generated by Django 4.1.8 on 2023-06-15 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routeplanning", "0025_rename_start_time_routesettings_departure_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routesettings",
            old_name="end_time",
            new_name="finish_time",
        ),
    ]
