# Generated by Django 3.1 on 2023-03-13 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('org_type', models.CharField(choices=[('Asset', 'Asset'), ('Brokerage', 'Brokerage'), ('Both', 'Both')], default='Asset', help_text='The type of organization.', max_length=10, verbose_name='Organization Type')),
                ('currency', models.CharField(default='USD', help_text='The currency that the organization uses', max_length=255, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
