# Generated by Django 4.1.8 on 2023-06-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fleets", "0017_alter_driver_displayname_alter_driver_phone"),
        ("organization", "0009_alter_organization_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("code", models.CharField(blank=True, editable=False, max_length=100)),
                ("distance", models.CharField(blank=True, max_length=100, null=True)),
                ("load", models.CharField(blank=True, max_length=100)),
                (
                    "utilization",
                    models.CharField(
                        blank=True, editable=False, max_length=100, null=True
                    ),
                ),
                (
                    "num_stops",
                    models.CharField(
                        blank=True, default=1, editable=False, max_length=100
                    ),
                ),
                ("departure_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "fuel_consumption",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_completion_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("completed_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("assigned", "assigned"),
                            ("dispatched", "dispatched"),
                            ("ongoing", "ongoing"),
                            ("completed", "completed"),
                        ],
                        default="STATUS_ASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_trips",
                        to="fleets.driver",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
