# Generated by Django 4.1.8 on 2023-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="code",
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_code",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
