# Generated by Django 4.1.8 on 2023-06-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_remove_trip_fuel_consumption_alter_trip_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("assigned", "assigned"),
                    ("dispatched", "dispatched"),
                    ("ongoing", "ongoing"),
                    ("completed", "completed"),
                ],
                default="STATUS_PENDING",
                max_length=20,
            ),
        ),
    ]
