# Generated by Django 4.1.8 on 2023-06-16 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_alter_trip_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="trip_code",
            new_name="code",
        ),
    ]
