# Generated by Django 4.1.8 on 2023-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0005_rename_trip_code_trip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="estimated_completion_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
