# Generated by Django 4.1.8 on 2023-06-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0006_alter_trip_estimated_completion_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("assigned", "assigned"),
                    ("ongoing", "ongoing"),
                    ("completed", "completed"),
                ],
                default="STATUS_PENDING",
                max_length=20,
            ),
        ),
    ]
