# Generated by Django 4.1.8 on 2023-06-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0007_alter_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
