# Generated by Django 4.1.8 on 2023-06-17 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0008_alter_trip_departure_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="estimated_completion_time",
        ),
    ]
