# Generated by Django 4.1.8 on 2023-06-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0009_remove_trip_estimated_completion_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="estimated_completion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
