# Generated by Django 4.1.8 on 2023-06-17 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0011_rename_driver_trip_driver_displayname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="driver_displayName",
            new_name="driver",
        ),
    ]
