# Generated by Django 4.1.8 on 2023-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0012_rename_driver_displayname_trip_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="actual_departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
