# Generated by Django 4.1.8 on 2023-07-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0014_alter_trip_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("Awaiting_Assignment", "Awaiting_Assignment"),
                    ("assigned", "assigned"),
                    ("ongoing", "ongoing"),
                    ("completed", "completed"),
                ],
                default="STATUS_PENDING",
                max_length=20,
            ),
        ),
    ]
