# Generated by Django 4.1.8 on 2023-07-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0012_alter_orguser_role"),
        ("trips", "0015_alter_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("", "Awaiting_Assignment"),
                    ("assigned", "assigned"),
                    ("ongoing", "ongoing"),
                    ("completed", "completed"),
                ],
                default="STATUS_PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "base_charge",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Base Charge"
                    ),
                ),
                (
                    "initial_distance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Amount"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Car"),
                            (" MotorCycle", "MotorCycle"),
                            ("VAN", "Van"),
                            ("PICKUP", "Pickup"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "amount_per_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Amount"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
