# Generated by Django 4.1.8 on 2023-07-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0016_alter_trip_status_ordercharges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercharges",
            name="amount_per_km",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount per km"
            ),
        ),
        migrations.AlterField(
            model_name="ordercharges",
            name="initial_distance",
            field=models.PositiveSmallIntegerField(verbose_name="Initial Distance"),
        ),
    ]
