# Generated by Django 4.1.8 on 2023-07-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0017_alter_ordercharges_amount_per_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercharges",
            name="amount_per_km",
            field=models.PositiveSmallIntegerField(verbose_name="Amount per extra km"),
        ),
        migrations.AlterField(
            model_name="ordercharges",
            name="initial_distance",
            field=models.PositiveSmallIntegerField(verbose_name="Initial Distance(Km)"),
        ),
    ]
