# Generated by Django 4.1.8 on 2023-07-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0012_alter_orguser_role"),
        ("trips", "0019_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Car"),
                            (" MotorCycle", "MotorCycle"),
                            ("VAN", "Van"),
                            ("PICKUP", "Pickup"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(verbose_name="load capacity"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "base_charge",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Base Charge"
                    ),
                ),
                (
                    "initial_distance",
                    models.PositiveSmallIntegerField(
                        verbose_name="Initial Distance(Km)"
                    ),
                ),
                (
                    "amount_per_km",
                    models.PositiveSmallIntegerField(
                        verbose_name="Amount per extra km"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "vehicle_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_charges",
                        to="trips.ordervehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="OrderCharges",
        ),
    ]
