# Generated by Django 4.1.8 on 2023-07-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0021_rename_vehicle_type_vehiclecharges_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vehicle_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="trips.ordervehicle",
            ),
            preserve_default=False,
        ),
    ]
