# Generated by Django 4.1.8 on 2023-07-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0022_order_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
