# Generated by Django 4.1.8 on 2023-07-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0023_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclecharges",
            name="pickup_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                max_digits=10,
                verbose_name="Base Charge",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("Awaiting_Assignment", "Awaiting_Assignment"),
                    ("assigned", "assigned"),
                    ("ongoing", "ongoing"),
                    ("completed", "completed"),
                ],
                default="STATUS_PENDING",
                max_length=20,
            ),
        ),
    ]
